#!/usr/bin/env python3
"""
knicks_2026_historic.py — pipeline orchestration for the
"Did the 2026 Knicks have a historic playoff run?" analysis.

Runs the whole thing in order: fetch data, render PNGs, run the analysis and
capture its stdout into RESULTS.md. Holds no data, plotting, or stats logic of
its own — it only sequences the other modules.

    MPLBACKEND=Agg python3 knicks_2026_historic.py

The analysis module is imported inside main() to keep import order explicit and
avoid surprises if it grows plotting dependencies later.
"""

import io
import contextlib

import knicks_2026_data as data       # noqa: F401  (used once metrics are added)
import knicks_2026_plots as plots     # noqa: F401  (used once plots are added)

RESULTS_PATH = "RESULTS.md"


def main() -> None:
    import knicks_2026_analysis as analysis

    # 1. Data  — TBD: fetch_* / compute_* calls (knicks_2026_data)
    # 2. Plots — TBD: plot_* calls (knicks_2026_plots), saving knicks_2026_*.png

    # 3. Analysis — capture stdout verbatim into RESULTS.md inside a ``` fence so
    #    generate_report.py's appendix parser can reproduce it.
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        analysis.run()

    with open(RESULTS_PATH, "w") as f:
        f.write("# Results\n\n")
        f.write("Auto-generated by `knicks_2026_analysis.py`. Do not edit by hand.\n\n")
        f.write("```\n")
        f.write(buf.getvalue())
        f.write("```\n")
    print(f"Wrote {RESULTS_PATH}")


if __name__ == "__main__":
    main()
