"""Render ``docs/*.md.j2`` templates to ``docs/*.md`` from the facts data model.

Every number cited in the prose comes from a fact (``docs/player_ranking_overview_facts.json``)
through the ``f()`` helper, so the documents cannot drift from the analysis. Run
this after the analysis pipeline (which writes facts.json) and before
``generate_report.py``.

Template delimiters are ``<< ... >>`` rather than Jinja's default ``{{ ... }}``,
because the docs use Quarto/Pandoc brace attributes (``{#fig-x}``, ``{.collapsible}``,
``{=typst}``) that would collide with Jinja's ``{{``/``{%``/``{#`` syntax.

Authoring/review helpers (stdlib only):
- ``--watch``     re-render whenever a template or facts.json changes (poll mtimes).
- ``--reference`` write ``docs/player_ranking_overview_facts_reference.md``: every fact in a table.
- ``--annotate``  render each ``f("name")`` as ``display [name]`` to ``*.annotated.md``
                  so a reviewer can see which fact backs each number.
"""
import glob
import json
import os
import sys
import time

import jinja2

DOCS_DIR = "docs"
FACTS_JSON = "docs/player_ranking_overview_facts.json"
REFERENCE_MD = "docs/player_ranking_overview_facts_reference.md"


def _make_env(facts_path: str = FACTS_JSON, annotate: bool = False) -> jinja2.Environment:
    with open(facts_path) as fh:
        records = json.load(fh)

    def f(name: str, fmt: str | None = None) -> str:
        """Display string for a fact. Pass `fmt` (e.g. "{:.2f}") to re-format the
        raw numeric value at a different precision than the fact's default, so a
        denser doc can reuse a fact at higher precision without a duplicate.

        In annotate mode the fact name is appended (``display [name]``) so a
        reviewer can confirm the right fact is wired to each number."""
        if name not in records:
            raise KeyError(f"unknown fact {name!r} referenced in template")
        rec = records[name]
        if fmt is not None and isinstance(rec["value"], (int, float)):
            display = fmt.format(rec["value"])
        else:
            display = rec["display"]
        return f"{display} [{name}]" if annotate else display

    env = jinja2.Environment(
        loader=jinja2.FileSystemLoader(DOCS_DIR),
        undefined=jinja2.StrictUndefined,
        autoescape=False,
        keep_trailing_newline=True,
        variable_start_string="<<",
        variable_end_string=">>",
        block_start_string="<%",
        block_end_string="%>",
        comment_start_string="<#",
        comment_end_string="#>",
    )
    env.globals["f"] = f
    # `tm` rewrites an ASCII hyphen-minus to a typographic minus (U+2212), for
    # docs (e.g. stats_explainer) that use − in negative numbers: << f(...)|tm >>.
    env.filters["tm"] = lambda s: s.replace("-", "−")
    return env


def render_all(facts_path: str = FACTS_JSON, annotate: bool = False) -> list[str]:
    """Render every ``docs/*.md.j2`` template.

    Default mode writes ``docs/<doc>.md`` (the real, byte-identical output).
    Annotate mode writes ``docs/<doc>.annotated.md`` instead, leaving the real
    ``.md`` untouched.
    """
    env = _make_env(facts_path, annotate=annotate)
    written = []
    for tpl_path in sorted(glob.glob(os.path.join(DOCS_DIR, "*.md.j2"))):
        if annotate:
            out_path = tpl_path[: -len(".md.j2")] + ".annotated.md"
        else:
            out_path = tpl_path[: -len(".j2")]
        template = env.get_template(os.path.basename(tpl_path))
        with open(out_path, "w") as fh:
            fh.write(template.render())
        written.append(out_path)
    return written


def _md_cell(text: str) -> str:
    """Escape a value for a single markdown table cell."""
    return str(text).replace("|", "\\|").replace("\n", " ")


def write_reference(facts_path: str = FACTS_JSON, out_path: str = REFERENCE_MD) -> str:
    """Write a markdown lookup table of every fact, grouped by name prefix.

    Columns: name | value (display) | unit | note. Sorted by name within each
    group (the part of the name before the first dot). This is a generated dev
    artifact: the lookup authors use while writing templates."""
    with open(facts_path) as fh:
        records = json.load(fh)

    groups: dict[str, list[str]] = {}
    for name in records:
        groups.setdefault(name.split(".")[0], []).append(name)

    lines = [
        "# Player ranking overview facts reference",
        "",
        "_Generated by `python3 render_docs.py --reference`. Do not edit by hand._",
        "",
        f"{len(records)} facts. Reference each in a template with "
        '`<< f("name") >>` (or `<< f("name", "{:.2f}") >>` to re-format the raw value).',
        "",
    ]
    for group in sorted(groups):
        lines.append(f"## {group}")
        lines.append("")
        lines.append("| name | value (display) | unit | note |")
        lines.append("|---|---|---|---|")
        for name in sorted(groups[group]):
            rec = records[name]
            unit = rec.get("unit") or ""
            note = rec.get("note") or ""
            lines.append(
                f"| `{name}` | {_md_cell(rec['display'])} "
                f"| {_md_cell(unit)} | {_md_cell(note)} |"
            )
        lines.append("")

    text = "\n".join(lines)
    with open(out_path, "w") as fh:
        fh.write(text)
    return out_path


def _snapshot(facts_path: str) -> dict[str, float]:
    """Modification times for every watched file (templates + facts.json)."""
    watched = glob.glob(os.path.join(DOCS_DIR, "*.md.j2")) + [facts_path]
    snap = {}
    for path in watched:
        try:
            snap[path] = os.path.getmtime(path)
        except OSError:
            pass
    return snap


def watch(facts_path: str = FACTS_JSON, interval: float = 0.5) -> None:
    """Re-render whenever a template or facts.json changes. Runs until Ctrl-C."""
    print(
        f"watching {DOCS_DIR}/*.md.j2 and {facts_path} "
        f"(every {interval}s; Ctrl-C to stop)"
    )
    for path in render_all(facts_path):
        print(f"rendered {path}")
    last = _snapshot(facts_path)
    try:
        while True:
            time.sleep(interval)
            current = _snapshot(facts_path)
            if current == last:
                continue
            changed = sorted(
                p for p in set(current) | set(last)
                if current.get(p) != last.get(p)
            )
            print(f"change in {', '.join(changed)}; re-rendering")
            try:
                for path in render_all(facts_path):
                    print(f"  rendered {path}")
            except Exception as exc:  # keep watching after a bad template/facts edit
                print(f"  render failed: {exc}")
            last = _snapshot(facts_path)
    except KeyboardInterrupt:
        print("\nstopped watching")


if __name__ == "__main__":
    args = sys.argv[1:]
    if not args:
        for path in render_all():
            print(f"rendered {path}")
    elif args == ["--watch"]:
        watch()
    elif args == ["--reference"]:
        print(f"wrote {write_reference()}")
    elif args == ["--annotate"]:
        for path in render_all(annotate=True):
            print(f"rendered {path}")
    else:
        print("usage: render_docs.py [--watch | --reference | --annotate]")
        sys.exit(2)
