"""
nbakit.report — build a FINDINGS.md → PDF report.

The rendering engine is shared; project-specific text (title, subtitle, data
credit line, footnote, appendix description, paths) is supplied via ReportConfig.

    from nbakit.report import ReportConfig, build_report
    build_report(ReportConfig(
        title="My Analysis",
        subtitle="A deep dive",
        data_line="Data: NBA.com · 1983–84 through 2025–26 · 52,399 games",
        footnote="See Appendix A for full tables.",
        appendix_desc="Auto-generated by analysis.py each run.",
        output_path="generated/report.pdf",
        pipeline_cmd="MPLBACKEND=Agg python3 run_analysis.py",
    ))
"""

import os
import re
import sys
from dataclasses import dataclass, field
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    HRFlowable,
    Image,
    KeepTogether,
    PageBreak,
    Paragraph,
    Preformatted,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from nbakit.mdpdf import (
    MONO,
    _draw_footer,
    _md_inline,
    _parse_regression_sections,
    _results_text,
)

PAGE_W, PAGE_H = letter
MARGIN    = 0.85 * inch
CONTENT_W = PAGE_W - 2 * MARGIN

DARK   = "#2c2c2a"
MID    = "#666666"
BLUE   = "#1f77b4"
ACCENT = BLUE


# ── Config ─────────────────────────────────────────────────────────────────────

@dataclass
class ReportConfig:
    title: str
    subtitle: str = ""
    author: str = "Justin Pietsch"
    data_line: str = ""
    footnote: str = ""
    appendix_desc: str = "Auto-generated each run."
    findings_path: str = "FINDINGS.md"
    results_path: str = "RESULTS.md"
    output_path: str = "generated/report.pdf"
    pipeline_cmd: str = "python3 analysis.py"


# ── Styles ─────────────────────────────────────────────────────────────────────

def _build_styles() -> dict:
    base = getSampleStyleSheet()
    return {
        **{k: base[k] for k in base.byName},
        "cover_title": ParagraphStyle(
            "cover_title", parent=base["Title"],
            fontSize=30, textColor=colors.HexColor(DARK),
            spaceAfter=10, alignment=TA_CENTER,
        ),
        "cover_sub": ParagraphStyle(
            "cover_sub", parent=base["Normal"],
            fontSize=13, textColor=colors.HexColor(MID),
            spaceAfter=5, alignment=TA_CENTER,
        ),
        "h1": ParagraphStyle(
            "h1", parent=base["Heading1"],
            fontSize=17, textColor=colors.HexColor(DARK),
            spaceBefore=16, spaceAfter=6,
        ),
        "h2": ParagraphStyle(
            "h2", parent=base["Heading2"],
            fontSize=12, textColor=colors.HexColor(ACCENT),
            spaceBefore=10, spaceAfter=4,
        ),
        "body": ParagraphStyle(
            "body", parent=base["Normal"],
            fontSize=10, leading=15,
            textColor=colors.HexColor(DARK),
            alignment=TA_JUSTIFY, spaceAfter=7,
        ),
        "caption": ParagraphStyle(
            "caption", parent=base["Normal"],
            fontSize=8.5, leading=12,
            textColor=colors.HexColor(MID),
            alignment=TA_CENTER, spaceAfter=14,
        ),
        "toc_num": ParagraphStyle(
            "toc_num", parent=base["Normal"],
            fontSize=11, textColor=colors.HexColor(ACCENT),
            alignment=TA_CENTER,
        ),
        "toc_title": ParagraphStyle(
            "toc_title", parent=base["Normal"],
            fontSize=11, textColor=colors.HexColor(DARK),
            leading=15,
        ),
        "note": ParagraphStyle(
            "note", parent=base["Normal"],
            fontSize=8.5, leading=12,
            textColor=colors.HexColor(MID),
            spaceAfter=5,
        ),
        "code": ParagraphStyle(
            "code", parent=base["Code"],
            fontSize=7, leading=9.5,
            textColor=colors.HexColor(DARK),
            fontName=MONO, spaceAfter=0,
        ),
        "appendix_section": ParagraphStyle(
            "appendix_section", parent=base["Normal"],
            fontSize=9, leading=12,
            textColor=colors.HexColor(ACCENT),
            fontName="Helvetica-Bold",
            spaceBefore=6, spaceAfter=3,
        ),
        "table_header": ParagraphStyle(
            "table_header", parent=base["Normal"],
            fontSize=9, leading=12,
            textColor=colors.white,
            fontName="Helvetica-Bold",
        ),
        "table_body": ParagraphStyle(
            "table_body", parent=base["Normal"],
            fontSize=9, leading=12,
            textColor=colors.HexColor(DARK),
        ),
    }


_STYLES = _build_styles()


# ── FINDINGS.md parser ─────────────────────────────────────────────────────────

def _parse_findings(path: str) -> dict[str, str]:
    if not os.path.exists(path):
        return {}
    with open(path) as f:
        content = f.read()
    sections = {}
    for part in re.split(r"^## ", content, flags=re.MULTILINE)[1:]:
        newline = part.find("\n")
        heading = part[:newline].strip()
        body = part[newline:].strip()
        body = re.sub(r"\n?---\s*$", "", body).strip()
        sections[heading] = body
    return sections


# ── Flowable helpers ───────────────────────────────────────────────────────────

def _img(path, width=None, max_height=None):
    if not os.path.exists(path):
        return Paragraph(f"[Missing image: {path}]", _STYLES["note"])
    if width is None:
        width = CONTENT_W
    ri = Image(path)
    aspect = ri.imageHeight / ri.imageWidth
    ri.drawWidth  = width
    ri.drawHeight = width * aspect
    if max_height and ri.drawHeight > max_height:
        ri.drawHeight = max_height
        ri.drawWidth  = max_height / aspect
    ri.hAlign = "CENTER"
    return ri


def _hr():
    return HRFlowable(width="100%", thickness=0.5,
                      color=colors.HexColor("#dddddd"), spaceAfter=8)


def _table(data, col_widths, header_rows=1):
    style = [
        ("BACKGROUND",     (0, 0), (-1, header_rows - 1), colors.HexColor(ACCENT)),
        ("TEXTCOLOR",      (0, 0), (-1, header_rows - 1), colors.white),
        ("FONTNAME",       (0, 0), (-1, header_rows - 1), "Helvetica-Bold"),
        ("FONTSIZE",       (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, header_rows), (-1, -1),
         [colors.HexColor("#f7f7f5"), colors.white]),
        ("GRID",           (0, 0), (-1, -1), 0.5, colors.HexColor("#dddddd")),
        ("TOPPADDING",     (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING",  (0, 0), (-1, -1), 5),
        ("LEFTPADDING",    (0, 0), (-1, -1), 6),
        ("RIGHTPADDING",   (0, 0), (-1, -1), 6),
    ]
    return Table(data, colWidths=col_widths, style=TableStyle(style))


def _chart(path, caption_text, width=None, max_height=None):
    return KeepTogether([
        _img(path, width=width, max_height=max_height),
        Spacer(1, 4),
        Paragraph(caption_text, _STYLES["caption"]),
    ])


def _md_to_flowables(text: str) -> list:
    flowables = []
    for block in re.split(r"\n{2,}", text):
        block = block.strip()
        if not block:
            continue
        if block.startswith("### "):
            flowables.append(Paragraph(_md_inline(block[4:]), _STYLES["h2"]))
        elif block.startswith("!["):
            m = re.match(r"!\[([^\]]*)\]\(([^)]+)\)(?:\{([^}]+)\})?", block)
            if m:
                opts = dict(kv.split("=") for kv in (m.group(3) or "").split()
                            if "=" in kv)
                w  = CONTENT_W * float(opts["width"])  if "width"  in opts else None
                mh = PAGE_H    * float(opts["height"]) if "height" in opts else None
                flowables.append(Spacer(1, 0.1 * inch))
                flowables.append(_chart(m.group(2), m.group(1), width=w, max_height=mh))
        elif block.startswith("- "):
            for line in block.splitlines():
                if line.startswith("- "):
                    flowables.append(
                        Paragraph("• " + _md_inline(line[2:]), _STYLES["body"]))
        elif block.startswith("|"):
            rows, is_header = [], True
            for line in block.splitlines():
                line = line.strip()
                if not line:
                    continue
                if re.match(r"^\|[\s\-:|]+\|$", line):
                    is_header = False
                    continue
                style = _STYLES["table_header"] if is_header else _STYLES["table_body"]
                cells = [Paragraph(_md_inline(c.strip()), style)
                         for c in line.split("|")[1:-1]]
                rows.append(cells)
                is_header = False
            if rows:
                n_cols = max(len(r) for r in rows)
                col_w = CONTENT_W / n_cols
                flowables.append(Spacer(1, 0.1 * inch))
                flowables.append(_table(rows, [col_w] * n_cols))
        else:
            joined = " ".join(ln.strip() for ln in block.splitlines() if ln.strip())
            flowables.append(Paragraph(_md_inline(joined), _STYLES["body"]))
    return flowables


# ── Cover ──────────────────────────────────────────────────────────────────────

def _cover(cfg: ReportConfig, sections: dict) -> list:
    toc_data = []
    for heading in sections:
        parts = heading.split(". ", 1)
        if len(parts) == 2 and parts[0].isdigit():
            toc_data.append([parts[0] + ".", parts[1], f"sec{parts[0]}"])
    toc_data.append(["A.", "Appendix: Full Analysis Output", "secA"])

    cover = [
        Spacer(1, 0.5 * inch),
        Paragraph(cfg.title, _STYLES["cover_title"]),
    ]
    if cfg.subtitle:
        cover.append(Paragraph(cfg.subtitle, _STYLES["cover_sub"]))
    cover += [
        Spacer(1, 0.15 * inch),
        Paragraph(cfg.author, _STYLES["cover_sub"]),
        Spacer(1, 0.25 * inch),
        _hr(),
        Spacer(1, 0.15 * inch),
    ]
    if cfg.data_line:
        cover.append(Paragraph(cfg.data_line, _STYLES["cover_sub"]))
    cover += [
        Paragraph(f"Generated {datetime.now().strftime('%B %d, %Y at %H:%M')}",
                  _STYLES["cover_sub"]),
        Spacer(1, 0.25 * inch),
        Paragraph("Contents", _STYLES["h2"]),
        Table(
            [[Paragraph(f'<a href="#{anchor}">{num}</a>', _STYLES["toc_num"]),
              Paragraph(f'<a href="#{anchor}">{title}</a>', _STYLES["toc_title"])]
             for num, title, anchor in toc_data],
            colWidths=[CONTENT_W * 0.10, CONTENT_W * 0.90],
            style=TableStyle([
                ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
                ("TOPPADDING",    (0, 0), (-1, -1), 4),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("LINEBELOW",     (0, -1), (-1, -1), 0.5, colors.HexColor("#dddddd")),
            ]),
        ),
        PageBreak(),
    ]
    return cover


# ── Appendix ──────────────────────────────────────────────────────────────────

def _appendix(cfg: ReportConfig) -> list:
    sections = _parse_regression_sections(_results_text(cfg.results_path))
    flowables: list = [
        PageBreak(),
        Paragraph('<a name="secA"/>Appendix A: Full Analysis Output', _STYLES["h1"]),
        _hr(),
        Paragraph(cfg.appendix_desc, _STYLES["body"]),
        Spacer(1, 0.1 * inch),
    ]
    for title, body in sections:
        if title:
            flowables.append(Spacer(1, 0.08 * inch))
            flowables.append(Paragraph(title, _STYLES["appendix_section"]))
        flowables.append(Preformatted(body, _STYLES["code"]))
    return flowables


# ── Prerequisites check ────────────────────────────────────────────────────────

def _check_prerequisites(cfg: ReportConfig) -> None:
    with open(cfg.findings_path) as f:
        content = f.read()
    missing_pngs = [
        m.group(1)
        for m in re.finditer(r"!\[[^\]]*\]\(([^)]+\.png)\)", content)
        if not os.path.exists(m.group(1))
    ]
    if missing_pngs:
        print("WARNING: The following chart(s) are missing and will appear as placeholders:\n")
        for p in missing_pngs:
            print(f"  {p}")
        print()
    if not os.path.exists(cfg.results_path):
        print(f"ERROR: {cfg.results_path} is missing.\n")
        print(f"Run the analysis pipeline first:\n\n  {cfg.pipeline_cmd}\n")
        print("Then retry:\n\n  python3 generate_report.py")
        sys.exit(1)


# ── Public API ─────────────────────────────────────────────────────────────────

def build_report(cfg: ReportConfig) -> None:
    os.makedirs(os.path.dirname(cfg.output_path) or ".", exist_ok=True)
    _check_prerequisites(cfg)
    sections = _parse_findings(cfg.findings_path)

    story = [*_cover(cfg, sections)]
    for heading, body in sections.items():
        num_str = heading.split(".")[0]
        if num_str.isdigit() and int(num_str) >= 4:
            story.append(PageBreak())
        anchor = f'<a name="sec{num_str}"/>' if num_str.isdigit() else ""
        story += [Paragraph(anchor + heading, _STYLES["h1"]), _hr(),
                  *_md_to_flowables(body)]

    if cfg.footnote:
        story += [Spacer(1, 0.3 * inch), _hr(),
                  Paragraph(cfg.footnote, _STYLES["note"])]

    story += _appendix(cfg)

    SimpleDocTemplate(
        cfg.output_path, pagesize=letter,
        leftMargin=MARGIN, rightMargin=MARGIN,
        topMargin=MARGIN, bottomMargin=MARGIN,
        title=cfg.title, author=cfg.author,
    ).build(story, onFirstPage=_draw_footer, onLaterPages=_draw_footer)
    print(f"Saved → {cfg.output_path}")
