#!/usr/bin/env python3
"""
Generate the 2026 Knicks historic-playoffs PDF report.
Run after knicks_2026_historic.py — all PNGs and RESULTS.md must exist.

    python3 generate_report.py
"""

import os

from nbakit.report import ReportConfig, build_report

OUTPUT_DIR = "generated"

if __name__ == "__main__":
    build_report(ReportConfig(
        findings_path="knicks_2026_historic_FINDINGS.md",
        title="Did the 2026 Knicks Have a Historic Playoff Run?",
        subtitle="The 2025–26 New York Knicks in Context",
        data_line="Data: NBA.com via nba_api",
        footnote=(
            "Data: NBA.com via nba_api. The 2025–26 Knicks playoff run is ranked "
            "against historical playoff runs. See Appendix A for the full analysis output."
        ),
        appendix_desc=(
            'Auto-generated by <font name="Courier">knicks_2026_analysis.py</font> '
            "each time the analysis is run."
        ),
        output_path=os.path.join(OUTPUT_DIR, "knicks_2026_historic_report.pdf"),
        pipeline_cmd="MPLBACKEND=Agg python3 knicks_2026_historic.py",
    ))
