"""PROJECT pipeline orchestrator.

Sequences: data → plots → analysis → docs/PROJECT_results.md.
Run with: MPLBACKEND=Agg python3 PROJECT.py
"""
import io
import os
import sys


def main() -> None:
    import PROJECT_data as data        # noqa: F401 (populate when data layer exists)
    import PROJECT_plots as plots      # noqa: F401 (call plot_* functions here)

    os.makedirs("generated/images", exist_ok=True)

    # TODO: call data fetch/compute functions, then plot_* functions.

    # Run analysis and capture output into results.md.
    import PROJECT_analysis as analysis
    buf = io.StringIO()
    analysis.run(buf)
    results = buf.getvalue()

    results_path = "docs/PROJECT_results.md"
    with open(results_path, "w") as fh:
        fh.write("# PROJECT Results\n\n")
        fh.write("Auto-generated by `PROJECT.py`. Never edit manually — re-run the pipeline to refresh.\n\n")
        fh.write("```\n")
        fh.write(results)
        fh.write("```\n")

    print(f"wrote {results_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
